### PR TITLE
Add seed option to random_label_cmap

### PR DESCRIPTION
**Pull request by hwarden162**
Add a seed option to the random_label_cmap function that will not be used by default, but will allow users to colour multiple images of the plot such that each nucleus uses the same colour.

### CODE REVIEW

**Comment by uschmidt83** [comment]
Hi @hwarden162, thanks for opening this PR.

I'm not sure I understand why this is needed though. Couldn't one just call `np.random.seed(seed)` before `random_label_cmap()`? Also, if the goal is to use the same colormap several times, why not store it in a variable and re-use it several times?

**Comment by maweigert** [comment]
I would support such a parameter on the grounds that it would make the cmap creation optionally deterministic (e.g. when sharing code snippets). I would however suggest not doing this via global seed setting but by creating and using a local `rng=np.random.RandomState(seed)` such to avoid the side effect of secretly manipulating the global numpy rng state.

**Comment by uschmidt83** [comment]
> I would however suggest not doing this via global seed setting but by creating and using a local `rng=np.random.RandomState(seed)` such to avoid the side effect of non-transparently manipulating the global numpy rng state.

I would've suggested the same, but I still don't understand why this is necessary. Why not simply do this?
```python
# np.random.seed(seed)  # optional
my_cmap = random_color_cmap()
...
plt.imshow(..., cmap=my_cmap)
...
plt.imshow(..., cmap=my_cmap)
```

**Comment by maweigert** [comment]
> Why not simply do this?

bc it might be nice to have the same cmap across multiple runs of a script (e.g. when generating figures etc)

**Comment by uschmidt83** [comment]
> bc it might be nice to have the same cmap across multiple runs of a script (e.g. when generating figures etc)

Calling `np.random.seed(seed)` seems good enough in this case.

**Comment by hwarden162** [comment]
I have added another commit to not alter the global rng state, this is a very good point I did not see. I use this as I perform some post processing on the mask (specific to my use case) and I then want to display the original and the processed masks side by side but with the matching colours. I understand that I could just set the state myself. At the moment I have a function that wraps this function and sets the random state for me, but I thought this might be cleaner. It might not be a use case that others need often though.

**Comment by maweigert** [comment]
lgtm, thanks!

**Pull request merged**
